#! bin/bash
mkdir terraform
cd terraform
touch variable.tf
touch output.tf
touch provider.tf
touch data.tf
touch terraform.tfvars
## iam
touch iam.tf
touch iam_role.tf
mkdir iam_role
touch iam_role/{main.tf,output.tf,variable.tf,data.tf}
## network
touch vpc.tf
touch subnet.tf
touch route_table.tf
touch internet_gateway.tf
touch alb.tf
touch eip.tf
touch nat_gateway.tf
## security_groups
touch security_group.tf
mkdir security_group
touch security_group/{main.tf,output.tf,variable.tf,data.tf}
## container
touch ecr.tf
touch ecs.tf
mkdir task-definitions
touch task-definitions/{frontend.json,backend.json}
## database
touch rds.tf
## s3
touch s3.tf
## surveillance
touch cloudwatch.tf
## key-management
touch kms.tf
touch ssm.tf
## route53
touch amc.tf
touch route53.tf