import "@/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import SessionProviderWrapper from "../components/SessionProviderWrapper";
import { getServerAuthSession } from "@/server/auth";
import { Toaster } from "@/app/_components/ui/toaster";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex min-h-screen flex-col items-center justify-center">
        <SessionProviderWrapper session={session}>
          {children}
          <Toaster />
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
